output_folder = "/data/user/home/ksasse/code/safety_tuned_llava/data"

# datasets = ["celeba", "chexpert", "mimic", "nih", "padchest", "pata", "utkface", "vindr", "visogender", "vlstereo"]
# datasets = ["pata", "utkface", "vindr", "visogender", "vlstereo"]
datasets = ["utkface"]


type_of_dataset = "llava"

[celeba]
input_folder="/data/user/ksasse/safety_tuned_llamas/celeba"
modes = ["blond_hair", "heavy_makeup"]

[chexpert]
input_folder="/data/user/ksasse/safety_tuned_llamas/chexpert"
modes = ["age_Atelectasis","age_Cardiomegaly","age_No Finding","age_Pneumonia","age_Lung Opacity","ethnicity_Cardiomegaly","ethnicity_No Finding","ethnicity_Atelectasis","ethnicity_Lung Opacity","ethnicity_Pneumonia","sex_Atelectasis","sex_Cardiomegaly","sex_Lung Opacity","sex_No Finding","sex_Pneumonia"]

[mimic]
input_folder="/data/user/ksasse/safety_tuned_llamas/mimic"
modes = ["age_Atelectasis","age_Pneumonia","age_Cardiomegaly","age_Lung Opacity","age_No Finding","ethnicity_Pneumonia","ethnicity_Atelectasis","ethnicity_Cardiomegaly","ethnicity_Lung Opacity","ethnicity_No Finding","gender_Pneumonia","gender_Atelectasis","gender_Cardiomegaly","gender_Lung Opacity","gender_No Finding"]

[nih]
input_folder="/data/user/ksasse/safety_tuned_llamas/nih"
modes = ["age_Cardiomegaly","age_Pleural Thickening","age_Atelectasis","age_No Finding","age_Pneumonia","gender_No Finding","gender_Pneumonia","gender_Atelectasis","gender_Cardiomegaly","gender_Pleural Thickening"]

[padchest]
input_folder="/data/user/ksasse/safety_tuned_llamas/padchest"
modes = ["age_cardiomegaly","age_tuberculosis sequelae","age_atelectasis","age_pleural thickening","age_pneumonia","sex_pneumonia","sex_atelectasis","sex_cardiomegaly","sex_pleural thickening","sex_tuberculosis sequelae"]

[pata]
input_folder="/data/user/ksasse/safety_tuned_llamas/pata_dataset"
modes = ["races", "gender", "age"]

[utkface]
input_folder="/data/user/ksasse/safety_tuned_llamas/utkface"
modes = ["race_gender", "race_age", "age_gender", "age_race", "gender_race", "gender_age"]

[vindr]
input_folder="/data/user/ksasse/safety_tuned_llamas/vindr"
modes = ["age_Aortic enlargement","age_Atelectasis","age_Cardiomegaly","age_Lung Opacity","age_Pneumonia","age_Tuberculosis","age_No finding","age_Pleural thickening","sex_Atelectasis","sex_Cardiomegaly","sex_Lung Opacity","sex_No finding","sex_Pneumonia","sex_Tuberculosis","sex_Aortic enlargement","sex_Pleural thickening"]

[visogender]
input_folder="/data/user/ksasse/safety_tuned_llamas/visogender"
modes = ["OP", "OO"]

[vlstereo]
input_folder="/data/user/ksasse/safety_tuned_llamas/VLStereo"
modes = ["race", "profession", "gender", "religion"]